<?php

namespace CarDealerBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMake($make)
    {
        return $this->createQueryBuilder('car')
            ->where('car.make = :make')
            ->setParameter('make', $make)
            ->orderBy('car.model', 'asc')
            ->addOrderBy('car.travelledDistance', 'desc')
            ->getQuery()
            ->getResult();
    }

    public function findByPart($id)
    {
        return $this->createQueryBuilder('c')
//            ->select('c, p')
            ->innerJoin('c.parts', 'p')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
