<?php

namespace CarDealerBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $order
     * @return array
     */
    public function getAllCustomers($order) {
        return $this->createQueryBuilder('customer')
            ->orderBy('customer.birthDate', $order)
            ->addOrderBy('customer.isYoungDriver')
            ->getQuery()
            ->getResult();
    }
}
