<?php

namespace CarDealerBundle\Repository;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
//    /**
//         * @param string $order
//         * @return array
//         */
//    public function getAllCustomers($order) {
//        return $this->createQueryBuilder('supplier')
//            ->OrderBy('supplier.isImporter')
//            ->setParameter('sort', $order)
//            ->getQuery()
//            ->getResult();
//    }
}
